# Generated by Django 4.0 on 2022-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_count', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
