# Generated by Django 4.0 on 2022-04-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_cartweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartweb',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.productname'),
        ),
    ]
